server:
  address: 0.0.0.0
  port: ${PORT:8080}


spring:
  profiles:
    default: no-mtls
  application:
    name: "mTLS 101"

# Swagger UI config
springdoc:
  packagesToScan: "es.cabrerizo.mtls101.rest.controller"
  swagger-ui:
    operationsSorter: method

app:
  helloStr: "Hello unsecure world"
---
spring.config.activate.on-profile: one-way-tls
app:
  helloStr: "Hello naive client"
---
spring.config.activate.on-profile: two-ways-tls
app:
  helloStr: "Hello trusted client"
